[package]
name = "fuselage"
version = "0.1.0"
authors = ["foophoof <me@foophoof.com>"]
build = "build.rs"
publish = false
license = "MIT"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
